object Main extends App {
   println("Hello!")
// println(Day1.solve1)
// println(Day1.solve2)
//   println(Day2.solve1())
//   println(Day2.solve2())
   // println(Day3.solve1())
   // println(Day3.solve2())
   //  println(Day4.solve1())
   //  println(Day4.solve2())
   // println(Day5.solve1())
   // println(Day5.solve2())
//   println(Day6.solve1())
//   println(Day6.solve2())
   println(Day7.solve1())
//   println(Day7.solve2())
}
